# Generated by Django 3.1.5 on 2021-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210114_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
